params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd_dyros

  network:
    name: actor_critic_dyros
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.302585 # -2.9957 -> 1n(1/20)
        sigma_last:
          name: const_initializer
          val: -2.9957
        fixed_sigma: True

    mlp:
      units: [256, 256]
      activation: relu
      d2rl: False

      initializer:
        name: orthogonal_initializer
        gain: 0.01
      regularizer:
        name: None

    estimator_mlp:      
      units: [256, 128]
      activation: relu
      d2rl: False
      input_num: 217

      initializer:
        name: orthogonal_initializer
        gain: 0.01
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:DyrosDynamicWalk,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    mixed_precision: True
    normalize_input: False #default = True
    normalize_value: False #Need to change to False
    value_bootstrap: True
    clip_actions: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0 
    normalize_advantage: True 
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-5
    learning_rate_min: 3e-6
    lr_schedule: linear # could be adaptive, linear, constant # DH: should be linear
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:5000,${....max_iterations}}   # DH: u may play with this # GENE: 80000000 / 16384 * 2
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 0.5
    entropy_coef: 0.0
    truncate_grads: True
    ppo: True
    use_estimator_network: True
    e_clip: 0.2
    horizon_length: 128    # DH: u may play with this
    minibatch_size: 4096  # DH: u may play with this (num_envs*horizon_length/mini_batch_size should be minibatch_size!!!!!!!!!!)
    mini_epochs: 5
    critic_coef: 0.5
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 0.
    #wandb
    wandb_activate: False # True, False
    log_wandb_frequency: 10
    num_rewards: 14 #Modify with individual tasks 
    num_extra_logging: 1
    separate_opt: True #True only when trying to study with separate actor/critic